services:
  my-app:
    image: localhost:3001/mess9/fillost:latest
    container_name: my-app
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.my-app.rule=Host(`fil-lost.org`)
      - traefik.http.routers.my-app.entrypoints=web
      - traefik.http.services.my-app.loadbalancer.server.port=80

networks:
  proxy:
    external: true